#!/bin/bash


function makecert() {
	ca=$1
	dir=$2
	name=$3

	echo ""
	echo "Generating certificate for: ${name}"
	echo "Using CA: \"${ca}\""
	echo "Dir: ${dir}"

	mkdir -p ${dir}
	openssl genrsa -out ${dir}/${name}.key 2048
	openssl req -new -key ${dir}/${name}.key -out ${dir}/${name}.csr -subj "/CN=${name}"
	openssl ca -name ${ca} -in ${dir}/${name}.csr -out ${dir}/${name}.crt

}

makecert "CA_etcd" "./server/" "etcd-server"
makecert "CA_etcd" "./client/" "etcd-client"

exit

echo "generating server certificate"
openssl genrsa -out server/etcd-server.key 2048
openssl req -new -key server/etcd-server.key -out server/etcd-server.csr -subj '/CN=etcd-server'
sudo openssl ca -name CA_etcd -in server/etcd-server.csr -out server/etcd-server.crt


echo "generating client certificate"
openssl genrsa -out client/etcd-client.key 2048
openssl req -new -key client/etcd-client.key -out client/etcd-client.csr -subj '/CN=etcd-client'
sudo openssl ca -name CA_etcd -in client/etcd-client.csr -out client/etcd-client.crt

echo "generating node0 certificate"
openssl genrsa -out node0/etcd-node0.key 2048
openssl req -new -key node0/etcd-node0.key -out node0/etcd-node0.csr -subj '/CN=etcd-node0'
sudo openssl ca -name CA_etcd -in client/etcd-client.csr -out client/etcd-client.crt


echo "done."
exit

